### PR TITLE
[iOS] Use edited photo

### PR DESCRIPTION
**Pull request by krokyze**
Related to https://github.com/CaiJingLong/flutter_photo_manager/issues/184#issuecomment-724698564
Tested and now works as expected 👍

### CODE REVIEW

**Comment by CaiJingLong** [comment]
In fact, both first and last are wrong, we should use the asset type and resource count to judge.
I will try to use the new condition to get the edited data.

**Comment by CaiJingLong** [comment]
I commit a [branch][] to fix the problem.

[branch]: https://github.com/CaiJingLong/flutter_photo_manager/tree/fix-edited-data

**Comment by krokyze** [comment]
@CaiJingLong ok thanks, will take a look in that branch 👍

**Comment by krokyze** [comment]
@CaiJingLong just updated this PR with newest changes from master.

**Comment by CaiJingLong** [comment]
I will close this PR. If the commit cannot fix your problem, you can open a new PR to continue the fix.

Please use the newest dev version.

**Pull request closed without merging**
